### ISSUE TITLE
[Feature Request] - Fast Channel opening with a new peer

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL-Design#16]
The current flow of opening a channel with a new peer is:
1. Connect with a peer.
2. Open channel with the peer.

This flow can be shortened for better UX, by handling peer connection in the background.

**Comment by diogorsergio** [comment]
Addressed in commit: https://github.com/Ride-The-Lightning/RTL-Design/commit/adc8f82c1073e99e18b175a7bb4e8bd0a6e5c1a5 with the following changes: 

Open Channel:
Removed ability to add peer within the open channel flow to keep funcitionality segmented.

Add Peer:
Updated flow to a stepper. 1st Step: Add Peer / 2nd Step: Open Channel (Optional).
