### ISSUE TITLE
Node setup config via the UI

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL-Design#37]
This feature can be used to edit the config params of an existing lightning node or add new params for a new node.
The parameters which need to be entered or modified by the user:
1. Node name - To identify your node in RTL
2. Lightning Implementation - LND or C-Lightning
3. Macaroon Path - Folder containing LND or C-Lightning-REST macaroons.
4. Lightning Server URL - The REST API server path to enable RTL to connect with the node e.g. `https://localhost:8080/v1`
5. Swap Server URL - The url for configuring connection with Loop server (This is an optional config, to enable connecting with loop service and only available for LND)

**Comment by diogorsergio** [comment]
Addressed and merged in PR: https://github.com/Ride-The-Lightning/RTL-Design/commit/af9603c002c0d051c9217666cada8f18cf371f3d

**Onboarding Flow:**
- Step 1: Introduction
- Step 2: Lightning Implementation
- --
**LND**
- Step 3.1 - LND: admin.macaroon
- Step 3.2 - LND: lnd.conf
- Step 3.3 - LND: lnServerUrl
- Step 3.4 - LND: Swap server
- --
**C-Lightning**
- Step 3.1 - C-Lightning: access.macaroon
- Step 3.2 - C-Lightning: config
- Step 3.2 - C-Lightning: lnServerUrl
- --
- Step 4: Finished!
