### ISSUE TITLE
RTL - Login page design

### ISSUE THREAD

**Issue by saubyk** [Ride-The-Lightning/RTL-Design#58]
Design RTL Login page, with a simple form to accept the password. The page should cover the below points:

1. RTL Logo
2. Welcome message
3. Form to capture the password with an option to switch the password entered and view it in plain text.
4. Button to Login (optional)

**Comment by swedishfrenchpress** [comment]
Hey @saubyk. I designed a simple login page that meet the 4 requirements. I'm open to suggestions on the copy and overall design. 

![rtl login 2](https://user-images.githubusercontent.com/78821053/107889934-2d01fa00-6f16-11eb-86fc-79a937f7abfe.png)
![rtl-login1](https://user-images.githubusercontent.com/78821053/107889935-2ecbbd80-6f16-11eb-8451-0261b2bc9b87.png)

**Comment by saubyk** [comment]
Hi @swedishfrenchpress this is awesome! Thanks a lot for taking a stab at it. :-)
Here is my first reaction, do let me know you think:
- Login page should not show the menu. Menu will become visible after the user logs in. So it should only be the login form.
- Change the message to `Welcome: Manage your lightning node`
- Remove the menu of capabilities

**Comment by swedishfrenchpress** [comment]
Thanks for the feedback @saubyk. I agree with the suggestion, it's good to scale back and keep only what's necessary. Especially for a login page. 
![rtl-login-rev2](https://user-images.githubusercontent.com/78821053/107983729-b53fd800-6fc6-11eb-9e7b-e1c91c071481.png)

**Comment by saubyk** [comment]
@swedishfrenchpress Love it! 😍

**Comment by diogorsergio** [comment]
Design addressed in: 

Commit: https://github.com/Ride-The-Lightning/RTL-Design/commit/84d3d8cc246e04f9d9e863baa49ac2d684a44697 PR: https://github.com/Ride-The-Lightning/RTL-Design/pull/59
